-- Legacy compatibility note.
-- This file was used by an older LinkedIn-only version of the app.
-- For the current Job Application Tracker + LinkedIn/CV Analytics schema, use:
--   001_schema.sql
--   002_rls_policies.sql
-- Existing deployments should use:
--   005_upgrade_to_job_tracker_platform.sql
--   002_rls_policies.sql
